### ISSUE TITLE
Explore Porting the exact logic in tests/drone_simulation.py to PettingZoo or Gym

### ISSUE THREAD

**Issue by weihangzheng** [BoundlessDevelopment/Capstone-Project#19]
Either copy over the functions and their bodies, or recreate with identical functionality.

Make sure all the logic is ported, and also some concrete tradeoff investigation of why it's better than plain Python.

**Comment by Thanoshan** [comment]
Closing this issue. Will not be implemented and we'll instead be looking at implementing something similar to the Baseline directly.
