### ISSUE TITLE
Implement DQN Algorithm

### ISSUE THREAD

**Issue by pandyah5** [BoundlessDevelopment/Capstone-Project#47]

**Comment by Thanoshan** [comment]
I'm actively using Ray currently to help with training and tuning, however we can also look into using something simpler like Stable Baselines as its much more user friendly to use (Ray has by far the steepest learning curve). CleanRL also has great implementations in one file format, if we eventually want to look into modifying every part of the process to be custom. Do note that Stable Baselines is built for single agent training. It can be applied to multiple agents but can only learn one policy at a time unlike Ray. Though training one policy may actually be better for our use case...

Preliminary findings from my implementations & experiments seem to have mixed results in full obs mode by trying some DQN and PPO methods with independent policy learning. Hyperparameters however were not tuned at this stage. Single policy may be better, but would require us to provide target neighbours or something as input for observations for the policy to be able to make a differentiation, which is something we should explore.
